---
apiVersion: v1
kind: Namespace
metadata:
  name: action-runner-test
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-runner
  namespace: action-runner-test
spec:
  template:
    spec:
      repository: "${target_repo}"
      labels:
      - test-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: action-runner-test-autoscaler
  namespace: action-runner-test
spec:
  minReplicas: 1
  maxReplicas: 30
  scaleTargetRef:
    kind: RunnerDeployment
    name: test-runner
  # metrics:
  # - type: PercentageRunnersBusy
  #   scaleUpThreshold: '0.75'
  #   scaleDownThreshold: '0.25'
  #   scaleUpFactor: '2'
  #   scaleDownFactor: '0.5'
  # scaleUpTriggers:
  #   - githubEvent:
  #       workflowJob: {}
  #     duration: "30m"
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    # A repository name is the REPO part of `github.com/OWNER/REPO`
    - "${target_repo}"
